# Generated by Django 2.0.1 on 2020-01-20 03:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_title_bold', models.CharField(default='Digital Ventures Group', max_length=255)),
                ('home_title_plane', ckeditor.fields.RichTextField(default='DVG is a common platform where product owners, agile leaders, designers and engineers collaborate to invent, design and develop new products and technologies or upgrade existing digital platforms.', max_length=255)),
                ('home_title_button_manifesto', models.CharField(default='Manifesto', max_length=50)),
                ('home_title_button_url', models.URLField(max_length=100)),
                ('home_we_garner', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('home_our_focus', models.CharField(default='Our Focus', max_length=50)),
                ('home_partners', models.CharField(default='Partners', max_length=100)),
                ('footer_title', models.CharField(default='Digital Ventures Group', max_length=100)),
                ('footer_links', models.CharField(default='Quick links', max_length=100)),
                ('footer_home_link', models.CharField(default='Home', max_length=50)),
                ('footer_home_url', models.URLField()),
                ('footer_whatwedo_link', models.CharField(default='What we do', max_length=50)),
                ('footer_whatwedo_url', models.URLField()),
                ('footer_manifesto_link', models.CharField(default='Manifesto', max_length=50)),
                ('footer_manifesto_url', models.URLField()),
                ('footer_joinus_link', models.CharField(default='Join us', max_length=50)),
                ('footer_joinus_url', models.URLField()),
                ('footer_contact_us', models.CharField(default='Contact us', max_length=50)),
                ('footer_contact_us_adress', models.CharField(default='Baku, AF Business House, floor 5', max_length=255)),
                ('footer_tel_text', models.CharField(default='+994 12', max_length=255)),
                ('footer_email', models.CharField(default='info@dvg.com', max_length=255)),
                ('facebook', models.URLField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True)),
                ('copyright', models.CharField(default='© Copyright 2020 - DVG. All rights reserved.', max_length=255)),
                ('footer_wp_link', models.TextField(default='#')),
                ('footer_wp_text', models.TextField(default='+994 50 444 2633')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
    ]
