# Generated by Django 2.0.1 on 2020-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200120_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='home_title_button_url',
            field=models.CharField(max_length=255),
        ),
    ]
