# Generated by Django 2.0.1 on 2020-01-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200120_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='footer_wp_link',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='footer_wp_text',
        ),
        migrations.AddField(
            model_name='settings',
            name='facebook_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='linkedin_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='mail',
            field=models.CharField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='mail_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter',
            field=models.CharField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='twitter_target',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='linkedin',
            field=models.CharField(blank=True, help_text='Example /about/ -page url', max_length=300, null=True),
        ),
    ]
