# Generated by Django 2.0.1 on 2020-01-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200120_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='logo_footer',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_header',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
        migrations.AddField(
            model_name='settings',
            name='logo_home',
            field=models.FileField(blank=True, null=True, upload_to='settings'),
        ),
    ]
