# Generated by Django 2.0.1 on 2020-01-20 05:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200120_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='home_we_garner',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
