# Generated by Django 2.0.1 on 2020-01-20 18:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200120_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurFocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Innovative solutions', max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Our Focus',
                'verbose_name_plural': 'Our Focus',
            },
        ),
    ]
