# Generated by Django 2.0.1 on 2020-01-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ourfocus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='partners')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
