# Generated by Django 2.0.1 on 2020-01-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='partners'),
        ),
    ]
