# Generated by Django 2.0.1 on 2020-01-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200121_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatwedo',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='title_main',
            field=models.TextField(),
        ),
    ]
