# Generated by Django 2.0.1 on 2020-01-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200121_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cases_title',
            field=models.CharField(blank=True, default='Cases', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='index_title',
            field=models.CharField(blank=True, default='What we do', max_length=255, null=True),
        ),
    ]
