# Generated by Django 2.0.1 on 2020-01-21 01:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200121_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cases_banking',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
