# Generated by Django 2.0.1 on 2020-01-21 01:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_settings_cases_banking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='cases_banking',
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cases_banking_content',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cases_banking_main',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='cases_banking_title',
            field=models.CharField(default='Banking', max_length=300),
        ),
    ]
