# Generated by Django 2.0.1 on 2020-01-21 01:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200121_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_banking_title', models.CharField(default='Banking', max_length=300)),
                ('cases_banking_main', ckeditor.fields.RichTextField()),
                ('cases_banking_content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='cases_banking_content',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='cases_banking_main',
        ),
        migrations.RemoveField(
            model_name='whatwedo',
            name='cases_banking_title',
        ),
    ]
