# Generated by Django 2.0.1 on 2020-01-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200121_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cases',
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_banking',
            field=models.CharField(default='Banking', max_length=300),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
