# Generated by Django 2.0.1 on 2020-01-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200121_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='cases_bold_content',
            new_name='cases_bold_content_banking',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='cases_bold_title',
            new_name='cases_bold_content_insurance',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='cases_plane_content',
            new_name='cases_plane_content_banking',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='cases_plane_title',
            new_name='cases_plane_content_insurance',
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_startup',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_telecom',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_banking',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_insurance',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_startup',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_telecom',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_insurance',
            field=models.CharField(default='Insurance', max_length=300),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_startup',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_telecom',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_banking',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_insurance',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_startup',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_telecom',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_startup',
            field=models.CharField(default='Startup', max_length=300),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_telecom',
            field=models.CharField(default='Telecom', max_length=300),
        ),
    ]
