# Generated by Django 2.0.1 on 2020-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_manifesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manifesto',
            name='title_plane',
            field=models.TextField(),
        ),
    ]
