# Generated by Django 2.0.1 on 2020-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_workshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='title',
        ),
        migrations.AddField(
            model_name='workshop',
            name='content_bold',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='content_plane',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='name',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_bold',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_main_bold',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_main_plane',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_plane',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
