# Generated by Django 2.0.1 on 2020-01-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200121_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
