# Generated by Django 2.0.1 on 2020-01-23 23:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200123_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='title_bold_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='joinus',
            name='title_bold_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='title_bold_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='title_bold_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='title_plane_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='title_plane_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='modalmenu',
            name='name_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modalmenu',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourfocus',
            name='content_az',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='ourfocus',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='ourfocus',
            name='title_az',
            field=models.CharField(default='Innovative solutions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourfocus',
            name='title_en',
            field=models.CharField(default='Innovative solutions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_banking_az',
            field=models.CharField(default='Banking', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_banking_en',
            field=models.CharField(default='Banking', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_banking_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_banking_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_insurance_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_insurance_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_startup_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_startup_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_telecom_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_content_telecom_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_banking_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_banking_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_insurance_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_insurance_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_startup_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_startup_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_telecom_az',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_bold_title_telecom_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_insurance_az',
            field=models.CharField(default='Insurance', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_insurance_en',
            field=models.CharField(default='Insurance', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_banking_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_banking_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_insurance_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_insurance_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_telecom_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_content_telecom_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_banking_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_banking_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_insurance_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_insurance_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_startup_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_startup_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_telecom_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_plane_title_telecom_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_startup_az',
            field=models.CharField(default='Startup', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_startup_en',
            field=models.CharField(default='Startup', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_telecom_az',
            field=models.CharField(default='Telecom', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_telecom_en',
            field=models.CharField(default='Telecom', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_title_az',
            field=models.CharField(blank=True, default='Cases', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='cases_title_en',
            field=models.CharField(blank=True, default='Cases', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='copyright_az',
            field=models.CharField(default='© Copyright 2020 - DVG. All rights reserved.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='copyright_en',
            field=models.CharField(default='© Copyright 2020 - DVG. All rights reserved.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_contact_us_adress_az',
            field=models.CharField(default='Baku, AF Business House, floor 5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_contact_us_adress_en',
            field=models.CharField(default='Baku, AF Business House, floor 5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_contact_us_az',
            field=models.CharField(default='Contact us', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_contact_us_en',
            field=models.CharField(default='Contact us', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_home_link_az',
            field=models.CharField(default='Home', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_home_link_en',
            field=models.CharField(default='Home', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_home_url_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_home_url_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_joinus_link_az',
            field=models.CharField(default='Join us', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_joinus_link_en',
            field=models.CharField(default='Join us', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_joinus_url_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_joinus_url_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_links_az',
            field=models.CharField(default='Quick links', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_links_en',
            field=models.CharField(default='Quick links', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_manifesto_link_az',
            field=models.CharField(default='Manifesto', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_manifesto_link_en',
            field=models.CharField(default='Manifesto', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_manifesto_url_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_manifesto_url_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_title_az',
            field=models.CharField(default='Digital Ventures Group', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_title_en',
            field=models.CharField(default='Digital Ventures Group', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_whatwedo_link_az',
            field=models.CharField(default='What we do', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_whatwedo_link_en',
            field=models.CharField(default='What we do', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_whatwedo_url_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_whatwedo_url_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_our_focus_az',
            field=models.CharField(default='Our Focus', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_our_focus_en',
            field=models.CharField(default='Our Focus', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_partners_az',
            field=models.CharField(default='Partners', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_partners_en',
            field=models.CharField(default='Partners', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_bold_az',
            field=models.CharField(default='Digital Ventures Group', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_bold_en',
            field=models.CharField(default='Digital Ventures Group', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_button_manifesto_az',
            field=models.CharField(default='Manifesto', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_button_manifesto_en',
            field=models.CharField(default='Manifesto', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_button_url_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_button_url_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_plane_az',
            field=ckeditor.fields.RichTextField(default='DVG is a common platform where product owners, agile leaders, designers and engineers collaborate to invent, design and develop new products and technologies or upgrade existing digital platforms.', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_title_plane_en',
            field=ckeditor.fields.RichTextField(default='DVG is a common platform where product owners, agile leaders, designers and engineers collaborate to invent, design and develop new products and technologies or upgrade existing digital platforms.', null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_we_garner_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='home_we_garner_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='joinus_title_az',
            field=models.CharField(default='Join us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='joinus_title_en',
            field=models.CharField(default='Join us', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='content_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_az',
            field=models.CharField(default='Strategic design & digital empowerment', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_en',
            field=models.CharField(default='Strategic design & digital empowerment', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_main_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='title_main_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='content_bold_az',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='content_bold_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='content_plane_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='content_plane_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='name_az',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='name_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_bold_az',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_bold_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_main_bold_az',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_main_bold_en',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_main_plane_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_main_plane_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_plane_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='title_plane_en',
            field=models.TextField(null=True),
        ),
    ]
