# Generated by Django 2.0.1 on 2020-01-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200124_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='not_found_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_name',
            field=models.CharField(blank=True, default='404 - Page not found', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_opps',
            field=models.CharField(blank=True, default='Oops!', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_title',
            field=models.CharField(blank=True, default='404 - Page not found', max_length=300, null=True),
        ),
    ]
