# Generated by Django 2.0.1 on 2020-01-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200127_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='not_found_content_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_content_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_name_az',
            field=models.CharField(blank=True, default='404 - Page not found', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_name_en',
            field=models.CharField(blank=True, default='404 - Page not found', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_opps_az',
            field=models.CharField(blank=True, default='Oops!', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_opps_en',
            field=models.CharField(blank=True, default='Oops!', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_title_az',
            field=models.CharField(blank=True, default='404 - Page not found', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='not_found_title_en',
            field=models.CharField(blank=True, default='404 - Page not found', max_length=300, null=True),
        ),
    ]
