# Generated by Django 2.0.1 on 2020-01-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200127_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='index_title_manifesto',
            field=models.CharField(blank=True, default='Manifesto', max_length=255, null=True),
        ),
    ]
