# Generated by Django 2.0.1 on 2020-01-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_settings_index_title_manifesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='index_title_manifesto_az',
            field=models.CharField(blank=True, default='Manifesto', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='index_title_manifesto_en',
            field=models.CharField(blank=True, default='Manifesto', max_length=255, null=True),
        ),
    ]
