# Generated by Django 2.0.1 on 2020-01-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200127_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='index_title_workshop',
            field=models.CharField(blank=True, default='workshops', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='index_title_workshop_az',
            field=models.CharField(blank=True, default='workshops', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='index_title_workshop_en',
            field=models.CharField(blank=True, default='workshops', max_length=255, null=True),
        ),
    ]
